const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const failures = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1365, height: 900 }, serviceWorkers: 'block' });
    context.setDefaultTimeout(15000);
    const page = await context.newPage();
    page.on('pageerror', error => failures.push(error.message));
    await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
    async function switchWorkspace(id) {
      await page.locator('#workspaceSwitchButton').click();
      await page.locator('[data-workspace-id="' + id + '"]').click();
    }
    const url = 'http://127.0.0.1:3000/?taxDemo=1&workspacePreview=1';
    await page.goto(url);
    await page.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === 'CPA备考 · 2026');
    assert.equal(await page.locator('#loginOverlay').isVisible(), false);
    // A duplicate tab inherits sessionStorage but must get a distinct writer.
    const firstWriter = await page.evaluate(() => sessionStorage.getItem('study:writer'));
    const duplicate = await context.newPage();
    await duplicate.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
    await duplicate.addInitScript(writer => sessionStorage.setItem('study:writer', writer), firstWriter);
    await duplicate.goto(url);
    await duplicate.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === 'CPA备考 · 2026');
    assert.notEqual(await duplicate.evaluate(() => sessionStorage.getItem('study:writer')), firstWriter);
    const originalStoreKey = await page.evaluate(() => Workspaces.key('cpa_subjects'));
    assert.notEqual(await duplicate.evaluate(() => Workspaces.key('cpa_subjects')), originalStoreKey);
    await duplicate.close();
    await page.locator('[data-tab=plan]').click();
    await switchWorkspace('demo-tax_advisor-2026');
    await page.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === '税务师备考 · 2026');
    assert.equal(await page.locator('[data-tab=plan]').evaluate(el => el.classList.contains('active')), true);
    await page.locator('[data-tab=tax]').click();
    await page.locator('[data-tax-chapter]').first().waitFor();
    assert.equal(await page.locator('[data-tax-chapter]').count(), 12);
    const taxSubjects = ['tax_law_i', 'tax_law_ii', 'tax_practice', 'tax_related_law', 'finance_accounting'];
    assert.deepEqual(await page.locator('#practiceSubjectSelect option').evaluateAll(options => options.map(o => o.value)), taxSubjects);
    for (const code of taxSubjects.slice(1)) {
      await page.locator('#practiceSubjectSelect').selectOption(code);
      if (code === 'tax_law_ii') {
        await page.waitForFunction(() => document.getElementById('practiceSubjectSelect')?.value === 'tax_law_ii' && document.querySelectorAll('[data-tax-chapter]').length === 10);
        assert.equal(await page.locator('#taxResumeBtn').isVisible(), false);
        continue;
      }
      await page.waitForFunction(value => document.getElementById('practiceSubjectSelect')?.value === value && document.querySelector('#taxChapterList .task-empty'), code);
      assert.equal(await page.locator('[data-tab=tax]').evaluate(el => el.classList.contains('active')), true);
      assert.equal(await page.locator('#practiceBankSelect').isDisabled(), true);
      assert.equal(await page.locator('#taxResumeBtn').isVisible(), false);
      await page.locator('[data-tax-scope=subjective]').click();
      await page.locator('#taxChapterList .task-empty').waitFor();
    }
    const output = path.join(__dirname, '..', 'work', 'workspace-tests');
    fs.mkdirSync(output, { recursive: true });
    await page.screenshot({ path: path.join(output, 'tax-entry-desktop.png'), fullPage: true });
    await page.locator('#workspaceSwitchButton').click();
    await page.screenshot({ path: path.join(output, 'workspace-switch-desktop.png'), fullPage: true });
    await page.locator('#workspaceSwitchClose').click();
    await page.locator('[data-tab=tasks]').click();
    const names = await page.evaluate(() => Store.getSubjects().map(subject => subject.name));
    assert.deepEqual(names, ['税法一', '税法二', '涉税服务实务', '涉税服务相关法律', '财务与会计']);
    await page.locator('.focus-start-btn[data-minutes="25"]').click();
    await page.locator('.focus-subject-option').first().click();
    await page.waitForTimeout(1100);
    await switchWorkspace('demo-cpa-2026');
    await page.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === 'CPA备考 · 2026');
    assert.equal(await page.locator('#focusTimerPanel').isVisible(), false);
    await switchWorkspace('demo-tax_advisor-2026');
    await page.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === '税务师备考 · 2026');
    await page.locator('[data-tab=tasks]').click();
    assert.match(await page.locator('#focusStateText').textContent(), /暂停/);
    await page.locator('#focusEndBtn').click();
    await page.locator('[data-action=end]').click();
    await page.locator('[data-focus-finish=save]').click();
    assert.equal(await page.evaluate(() => Store.getFocusSessions().length), 1);
    await page.locator('#workspaceNew').click();
    await page.locator('#workspaceCreateYear').fill('2027');
    await page.locator('#workspaceCopyTemplate').check();
    await page.locator('#workspaceCreateSave').click();
    await page.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === '税务师备考 · 2027');
    assert.equal(await page.evaluate(() => Store.getFocusSessions().length), 0);
    assert.equal(await page.evaluate(() => Store.getSubjects().length), 5);
    const summary = await page.evaluate(() => Focus.generateDailySummary());
    assert.match(summary, /^税务师 2027学习日报/);
    assert.ok(!summary.includes('NaN'));
    await switchWorkspace('demo-tax_advisor-2026');
    await page.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === '税务师备考 · 2026');
    assert.equal(await page.evaluate(() => Store.getFocusSessions().length), 1);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('[data-tab=tax]').click();
    await page.locator('#taxChapterList .task-empty').waitFor();
    assert.equal(await page.locator('[data-tab=tax]').evaluate(el => el.classList.contains('active')), true);
    await page.screenshot({ path: path.join(output, 'tax-entry-mobile.png'), fullPage: true });
    await page.locator('#workspaceSwitchButton').click();
    await page.screenshot({ path: path.join(output, 'workspace-switch-mobile.png'), fullPage: true });
    const bounds = await page.locator('#workspaceSwitchDialog').boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
    await page.locator('#workspaceSwitchClose').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.locator('[data-tab=tasks]').click();
    await page.screenshot({ path: path.join(output, 'tax-home-mobile.png'), fullPage: true });
    await switchWorkspace('demo-cpa-2026');
    await page.waitForFunction(() => document.getElementById('workspaceLabel')?.textContent === 'CPA备考 · 2026');
    await page.locator('[data-tab=tax]').click();
    await page.locator('[data-tax-chapter]').first().waitFor();
    await page.locator('[data-tax-chapter]').first().click();
    await page.locator('[data-tax-option]').first().waitFor();
    await page.locator('[data-tax-option]').first().click();
    await page.locator('#taxSubmitBtn').click();
    await page.waitForTimeout(200);
    await page.reload();
    await page.locator('#taxResumeBtn').waitFor();
    await page.locator('#practiceSubjectSelect').selectOption('accounting');
    await page.locator('#taxChapterList .task-empty').waitFor();
    assert.equal(await page.locator('#taxResumeBtn').isVisible(), false);
    await page.locator('#practiceSubjectSelect').selectOption('tax_law');
    await page.locator('#taxResumeBtn').waitFor();
    await switchWorkspace('demo-tax_advisor-2026');
    await page.locator('#taxChapterList .task-empty').waitFor();
    assert.equal(await page.locator('#practiceSubjectSelect').inputValue(), 'finance_accounting');
    assert.equal(await page.locator('#taxResumeBtn').isVisible(), false);
    assert.deepEqual(failures, []);
    console.log('PASS browser: duplicate-tab writer isolation, CPA/tax isolation, timer pause/restore, fresh year, preserved history, summary, CPA resume, desktop/mobile entry');
    await context.close();
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
